var Config = {
	error : {
		"empty_result" : "등록된 자료가 없습니다.",
		"true_insert" :	"저장이 성공하였습니다.",
		"false_insert" : "저장이 실패하였습니다.",
		"true_delete" : "삭제 되었습니다.", 
		"false_delete" : "삭제가 실패하였습니다.",
		"false_deletea" : "하위 메뉴가 존재하여 삭제가 실패하였습니다.",
		"empty_param" : "필요한 변수가 전달 되지 않았습니다.",
		"same_name" : "중복된 값이 존재합니다.",
		"same_uid" : "등록자가 동일합니다.",
		"same_join" : "이미 등록된 값이 존재합니다.",
		"invalid_input" : "값을 정확히 입력하여 주시기 바랍니다.",
		"invalid_id" : "아이디 값을 정확히 입력하여 주시기 바랍니다.",
		"invalid_passwd" : "비밀번호 값을 정확히 입력하여 주시기 바랍니다.",
		"invalid_member" : "회원 정보가 올바르지 않습니다.",
		"delete_member" : "삭제된 회원이거나 존재하지 않는 회원 정보입니다.",
		"invalid_ssn" : "주민등록 번호의 형식이 올바르지 않습니다.",
		"invalid_email" : "이메일의 형식이 올바르지 않습니다.",
		"invalid_search" : "검색값을 정확히 입력하여 주시기 바랍니다.",
		"invalid_admin" : "관리자 전용 페이지 입니다.",
		"invalid_login" : "로그인을 해주시기 바랍니다.",
		"member_only" : "사용자 전용 페이지입니다.",
		"unreservation_day" : "지정된 날짜는 예약 불가일입니다.",
		"empty_room" : "현재 등록 가능한 객실이 없습니다.",
		"max_limit_exceed" : "최대 예약 가능 개월을 초과하였습니다.",
		'invalid_admin' : '관리자 전용 페이지 입니다.',
		'unmatch_passwd' : "입력하신 패스워드가 일치하지 않습니다.",
		'invalid_reply' : '댓글을 작성할 수 있는 권한이 없습니다.',
		'send_false': 'sms전송이 실패하였습니다.',
		'already_check' : "이미 투표 하셧습니다.",
		'fail_mail' : '메일전송이 실패하였습니다.'
	}, 
	test : false
}